# Generated by Django 4.2.4 on 2023-10-08 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloRealTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temperatura', models.FloatField(default=-0.0, unique=True, verbose_name='temperatures')),
                ('Humedad', models.FloatField(default=-0.0, unique=True, verbose_name='Humidity%')),
                ('sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App1.modelolist')),
            ],
            options={
                'verbose_name': 'Dato_en_tiempo_real',
                'verbose_name_plural': 'Datos_en_tiempo_real',
                'db_table': 'Real_time',
            },
        ),
        migrations.CreateModel(
            name='ModeloHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('hour', models.TimeField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.modelolist')),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historial_de_datos',
                'db_table': 'History',
            },
        ),
    ]
