# Generated by Django 4.2.4 on 2023-09-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mimodelo',
            name='identificador',
        ),
        migrations.AlterField(
            model_name='mimodelo',
            name='temperatura',
            field=models.FloatField(max_length=10, unique=True, verbose_name='temperatures'),
        ),
    ]
