# Generated by Django 4.2.4 on 2023-10-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelohistory',
            options={'ordering': ['sensor', '-date'], 'verbose_name': 'Historial', 'verbose_name_plural': 'Historial_de_datos'},
        ),
        migrations.AlterModelOptions(
            name='modelolist',
            options={'verbose_name': 'Lista_sensor', 'verbose_name_plural': 'Lista-sensores'},
        ),
        migrations.RenameField(
            model_name='modelohistory',
            old_name='topic',
            new_name='sensor',
        ),
        migrations.AddField(
            model_name='modelohistory',
            name='Humedad',
            field=models.FloatField(default=-0.0, unique=True, verbose_name='Humidity%'),
        ),
        migrations.AddField(
            model_name='modelohistory',
            name='temperatura',
            field=models.FloatField(default=-0.0, unique=True, verbose_name='temperatures'),
        ),
        migrations.AlterModelTable(
            name='modelohistory',
            table='Historial',
        ),
        migrations.AlterModelTable(
            name='modelolist',
            table='Lista_sensores',
        ),
        migrations.AlterModelTable(
            name='modelorealtime',
            table='Tiempo_Real',
        ),
    ]
