# Generated by Django 4.2.4 on 2023-09-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_remove_mimodelo_identificador_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mimodelo',
            options={'verbose_name': 'Dato_en_tiempo_real', 'verbose_name_plural': 'Datos_en_tiempo_real'},
        ),
        migrations.AlterField(
            model_name='mimodelo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
